services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: ./fastapi-build/Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
